### ISSUE TITLE
Parsing schemas with (possibly external) refs

### ISSUE THREAD

**Issue by lvh** [metosin/scjsv#1]
I've been using this library to turn JSON Schema into clojure.spec (cc @ikitommi since I think you might care about this given that you're working on the opposite direction). Everything's working fine so far, except resolving refs, which is proving to be the trickiest part.

The example from the [JSON Schema validation spec](http://json-schema.org/latest/json-schema-core.html#anchor31) contains an `:id` with the bogus URI (incidentally a URL) `http://my.site/myschema#`. The full schema I'm using in my test is:

``` clojure
(def ref-schema
  "A simple schema with references.

  From http://json-schema.org/latest/json-schema-core.html#anchor30."
  {:$schema "http://json-schema.org/draft-04/schema#"
   :id "http://my.site/myschema#"
   :definitions {:schema1 {:id "schema1"
                           :type "integer"}
                 :schema2 {:type "array"
                           :items {:$ref "schema1"}}}})
```

Apparently the underlying json-schema-validator library supports a few schemes by default, but eventually does the resolution through java.net.URL. This results in the following error:

```
  actual: com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: unable to dereference URI "http://some.site/schema#"
    level: "fatal"
    uri: "http://some.site/schema#"
    exceptionMessage: "some.site"
```

The [examples from json-schema-validator](https://github.com/daveclayton/json-schema-validator/blob/master/src/main/java/com/github/fge/jsonschema/examples/Example10.java) suggest that this means I should specify a different `JsonSchemaFactory` using a different `LoadingConfiguration` (built using a `LoadingConfigurationBuilder` because Java). A related problem is inline vs canonical dereferencing: also specified on the `LoadingConfiguration` (which I think would fix this particular issue).

I can't do either right now, because the [`JsonSchemaFactory` is hardcoded](https://github.com/metosin/scjsv/blob/master/src/scjsv/core.clj#L17).

I'm volunteering to fix this, but I'm not sure what API you'd prefer. One option would be that you specify the `JsonSchemaFactory` to `validator` and `json-validator`. Another would probably be for the common use case of preloading a bunch of schemas, or using inline dereferencing. Perhaps we can have both: have the optional parameter be a JsonSchemaFactory and then have helper functions or something for building one. Suggestions (or at least an explicit "no preference") that would help said PR land much appreciated.

Apropos of inline vs canonical dereferencing: in my opinion, trying to resolve the id here looks pointless; the entire schema is self-contained. From what I gather from some tickets @fge (original author of json-schema-validator and other related libraries) seems to think the exact opposite, and he's worked with JSON Schema a lot more than I have, so I'm willing to defer judgement. Right now, my library for turning JSON Schema into clojure.spec always resolves URIs to their absolute form, but then only at the end tries to translate them to their generated clojure.spec names (since you don't necessarily know where definitions live, possibly in other schemas).

**Comment by miikka** [comment]
My preference is to have JsonSchemaFactory as an optional parameter. This way the common case stays as simple as it was and the complicated case becomes possible right now.
- This leaves the door open for implementing some helper functions for constructing the factories.
- Alternatively we could allow passing e.g. maps of preloaded schemas in addition to JsonSchemaFactories in the future.

I see that you added the optional JsonSchemaFactory parameter in #2. I'd be happy to merge it and do a release unless @ikitommi disagrees.

**Comment by lvh** [comment]
Awesome :) If you don't mind, I'd love a release after the PR is merged, since I'd like to use this feature and would prefer not to create forked releases :)

**Comment by ikitommi** [comment]
👍 

So, is/will there be an option to preload schemas somehow? Ring-swagger validator now load the JSON Schema file over the Internet, which is bad.

**Comment by miikka** [comment]
Merged the request and pushed out [`[metosin/scjsv "0.3.0"]`](https://clojars.org/metosin/scjsv). Thanks for the PR!

Tommi, I believe that passing in a suitable JsonSchemaFactory would indeed allow bundling the JSON-Schema schema file into ring-swagger instead of downloading it from Internet.

**Comment by lvh** [comment]
@ikitommi Yeah, this doesn't change any behavior yet because I wasn't sure if that's OK, but I definitely think like preloaded schemas + _never download anything_ is the way to go :) A lot of people who work on JSON Schema seem to disagree, maybe it's just because I'm a security nerd that "I'm going to go download some stuff over HTTP to see if this attacker-controlled input is valid" sounds like I'm not even going to think about it :)

**Comment by lvh** [comment]
@miikka Thanks for the release! Much appreciated. I will play with this a little and see what API I come up with. Do you have any particular contribution policy for e.g. helper libraries like camel-snake-kebab?

**Comment by miikka** [comment]
We do not have any contribution policy written down, apart from the usual stuff in [CONTRIBUTING.md](https://github.com/metosin/scjsv/blob/master/CONTRIBUTING.md). In general, we'd prefer to keep the amount of dependencies small for the libraries, but we do not have hard-and-fast rules about it. If there's a helper library that saves work, go for it.

However, specifically about camel-snake-kebab: in our experience, it's a library that breaks often and therefore we try to avoid it. It would be great if you could use something else - for example, ring-swagger uses [lettercase](https://github.com/ToBeReplaced/lettercase) instead.

**Comment by jvtrigueros** [comment]
@lvh I don't mean to resurrect this older thread, but were you able to get any progress going on that JSON Schema to Spec effort? I was looking into doing something similar. I want to generate data that matches a valide JSON Schema however my schemas also have local refs.

**Comment by lvh** [comment]
Nope.
