### ISSUE TITLE
Support for Draft 07

### ISSUE THREAD

**Issue by luposlip** [metosin/scjsv#16]
Cool lib, works great. But seemingly only up until draft-04 is supported by the used Java library.

Have you considered using this library instead, which supports draft-07?
https://github.com/everit-org/json-schema

**Comment by miikka** [comment]
Hi, as this library is basically a thin wrapper for [json-schema-validator](https://github.com/java-json-tools/json-schema-validator), I don't think we would be likely to switch the library. It'd be such a breaking change that we might as well create a new library for that purpose. Unfortunately it seems to me that json-schema-validator's development has stalled, so it's unlikely that it will ever have support for draft-07.

Thus if you have a pressing need for a draft-07 validator, I recommend either using everit-org's json-schema directly via Java interop or creating your own wrapper library for it.

**Comment by luposlip** [comment]
Thanks for your swift reply @miikka . I'm currently authoring an ultra-lightweight wrapper around the everit-one. It's so thin I'm not even sure it makes sense to publish it, but perhaps I'll do it anyway, if it works as expected.

**Comment by miikka** [comment]
@luposlip If you do publish it, let me know so that I can point to it in README, so that the next person looking for Draft-07 support can find it easily. :)

**Comment by luposlip** [comment]
👍🏽

ons. 28. nov. 2018 16.39 skrev Miikka Koskinen <notifications@github.com>:

**Comment by luposlip** [comment]
Hey @miikka - it's here:
https://github.com/luposlip/json-schema

**Comment by luposlip** [comment]
@miikka ? :)

**Comment by miikka** [comment]
Now mentioned in the README!
